### ISSUE TITLE
Limit Holdem Support?

### ISSUE THREAD

**Issue by markudevelop** [JakubPetriska/poker-cfr#1]
Hello Jakub, 

Thanks for sharing, I was wondering if you this could support limit holdem? I was interested in this because solving it could take a lot of storage so my next question do you have bucket support to be able to group it and make use less storage memory?

Thanks!

**Comment by JakubPetriska** [comment]
Hi, sorry abstractions are currently not available which makes Texas Hold'em case impossible due to the memory requirements. Sorry for super late reply.
