### ISSUE TITLE
how to efficiently compute the expect value at chance or opponent's decision points?

### ISSUE THREAD

**Issue by KK666-AI** [JakubPetriska/poker-cfr#6]
Cool works.

AIVAT needs to compute the expect values at the chance or opponent's decision points, however  computing expect values in large game, such as Texas Hold'em is time consuming. I wonder how to  define an efficient and effective value function? Thanks.

**Comment by JakubPetriska** [comment]
The repo is not meant for such large games. This is mentioned in the README:
> Current implementation only supports limit betting games and smaller games with up to 5 cards (hole cards + community cards). Many algorithms are also suited only for small Poker games like Leduc Hold'em.

**Comment by KK666-AI** [comment]
for small game, how do you compute the expect value?

**Comment by JakubPetriska** [comment]
In here https://github.com/JakubPetriska/poker-agent-kit/blob/master/verification/cfr_correctness_test.py#L104 how strategy that was trained using the CFR+ algorithm. First best response strategy is created and then expected player utilities are calculated. Note that these algorithms (best response and expected utilities) are calculated using naive enumeration.

**Comment by KK666-AI** [comment]
Thanks. it seems that in large game it's intractable to compute the expected value of one state.

**Comment by JakubPetriska** [comment]
Yes, that's true. Can I close this issue now?

**Comment by KK666-AI** [comment]
sure. Thanks.

**Comment by JakubPetriska** [comment]
Thanks for being interested in the repo. Hope it serves you well.
